spring:
  profiles:
    active: dev
  mvc:
    #当出现 404 错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  flyway:
    locations: classpath:sql
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mappers/*.xml

