package com.jyt.bbs.model.entity;

import java.io.Serializable;

public class AuthRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.condition
     *
     * @mbggenerated
     */
    private String condition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.ismenu
     *
     * @mbggenerated
     */
    private Boolean ismenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.createtime
     *
     * @mbggenerated
     */
    private Integer createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.updatetime
     *
     * @mbggenerated
     */
    private Integer updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.weigh
     *
     * @mbggenerated
     */
    private Integer weigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_rule.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_rule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.id
     *
     * @return the value of auth_rule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.id
     *
     * @param id the value for auth_rule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.type
     *
     * @return the value of auth_rule.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.type
     *
     * @param type the value for auth_rule.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.pid
     *
     * @return the value of auth_rule.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.pid
     *
     * @param pid the value for auth_rule.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.name
     *
     * @return the value of auth_rule.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.name
     *
     * @param name the value for auth_rule.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.title
     *
     * @return the value of auth_rule.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.title
     *
     * @param title the value for auth_rule.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.icon
     *
     * @return the value of auth_rule.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.icon
     *
     * @param icon the value for auth_rule.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.condition
     *
     * @return the value of auth_rule.condition
     *
     * @mbggenerated
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.condition
     *
     * @param condition the value for auth_rule.condition
     *
     * @mbggenerated
     */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.remark
     *
     * @return the value of auth_rule.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.remark
     *
     * @param remark the value for auth_rule.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.ismenu
     *
     * @return the value of auth_rule.ismenu
     *
     * @mbggenerated
     */
    public Boolean getIsmenu() {
        return ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.ismenu
     *
     * @param ismenu the value for auth_rule.ismenu
     *
     * @mbggenerated
     */
    public void setIsmenu(Boolean ismenu) {
        this.ismenu = ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.createtime
     *
     * @return the value of auth_rule.createtime
     *
     * @mbggenerated
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.createtime
     *
     * @param createtime the value for auth_rule.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.updatetime
     *
     * @return the value of auth_rule.updatetime
     *
     * @mbggenerated
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.updatetime
     *
     * @param updatetime the value for auth_rule.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.weigh
     *
     * @return the value of auth_rule.weigh
     *
     * @mbggenerated
     */
    public Integer getWeigh() {
        return weigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.weigh
     *
     * @param weigh the value for auth_rule.weigh
     *
     * @mbggenerated
     */
    public void setWeigh(Integer weigh) {
        this.weigh = weigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_rule.status
     *
     * @return the value of auth_rule.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_rule.status
     *
     * @param status the value for auth_rule.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_rule
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", icon=").append(icon);
        sb.append(", condition=").append(condition);
        sb.append(", remark=").append(remark);
        sb.append(", ismenu=").append(ismenu);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", weigh=").append(weigh);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}