package com.jyt.bbs.model.entity;

import java.io.Serializable;

public class AuthGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.createtime
     *
     * @mbggenerated
     */
    private Integer createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.updatetime
     *
     * @mbggenerated
     */
    private Integer updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.rules
     *
     * @mbggenerated
     */
    private String rules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.id
     *
     * @return the value of auth_group.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.id
     *
     * @param id the value for auth_group.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.pid
     *
     * @return the value of auth_group.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.pid
     *
     * @param pid the value for auth_group.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.name
     *
     * @return the value of auth_group.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.name
     *
     * @param name the value for auth_group.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.createtime
     *
     * @return the value of auth_group.createtime
     *
     * @mbggenerated
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.createtime
     *
     * @param createtime the value for auth_group.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.updatetime
     *
     * @return the value of auth_group.updatetime
     *
     * @mbggenerated
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.updatetime
     *
     * @param updatetime the value for auth_group.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.status
     *
     * @return the value of auth_group.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.status
     *
     * @param status the value for auth_group.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.rules
     *
     * @return the value of auth_group.rules
     *
     * @mbggenerated
     */
    public String getRules() {
        return rules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.rules
     *
     * @param rules the value for auth_group.rules
     *
     * @mbggenerated
     */
    public void setRules(String rules) {
        this.rules = rules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", status=").append(status);
        sb.append(", rules=").append(rules);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}