package com.jyt.bbs.model.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Post implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.perfect
     *
     * @mbggenerated
     */
    private Integer perfect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.overhead
     *
     * @mbggenerated
     */
    private Integer overhead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.see
     *
     * @mbggenerated
     */
    private Integer see;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.score
     *
     * @mbggenerated
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.qq_group
     *
     * @mbggenerated
     */
    private String qqGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.perfect
     *
     * @return the value of post.perfect
     *
     * @mbggenerated
     */
    public Integer getPerfect() {
        return perfect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.perfect
     *
     * @param perfect the value for post.perfect
     *
     * @mbggenerated
     */
    public void setPerfect(Integer perfect) {
        this.perfect = perfect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.overhead
     *
     * @return the value of post.overhead
     *
     * @mbggenerated
     */
    public Integer getOverhead() {
        return overhead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.overhead
     *
     * @param overhead the value for post.overhead
     *
     * @mbggenerated
     */
    public void setOverhead(Integer overhead) {
        this.overhead = overhead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_id
     *
     * @return the value of post.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_id
     *
     * @param userId the value for post.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.state
     *
     * @return the value of post.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.state
     *
     * @param state the value for post.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.area_id
     *
     * @return the value of post.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.area_id
     *
     * @param areaId the value for post.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.create_time
     *
     * @return the value of post.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.create_time
     *
     * @param createTime the value for post.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.type
     *
     * @return the value of post.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.type
     *
     * @param type the value for post.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.see
     *
     * @return the value of post.see
     *
     * @mbggenerated
     */
    public Integer getSee() {
        return see;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.see
     *
     * @param see the value for post.see
     *
     * @mbggenerated
     */
    public void setSee(Integer see) {
        this.see = see;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.score
     *
     * @return the value of post.score
     *
     * @mbggenerated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.score
     *
     * @param score the value for post.score
     *
     * @mbggenerated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.qq_group
     *
     * @return the value of post.qq_group
     *
     * @mbggenerated
     */
    public String getQqGroup() {
        return qqGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.qq_group
     *
     * @param qqGroup the value for post.qq_group
     *
     * @mbggenerated
     */
    public void setQqGroup(String qqGroup) {
        this.qqGroup = qqGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", perfect=").append(perfect);
        sb.append(", overhead=").append(overhead);
        sb.append(", userId=").append(userId);
        sb.append(", state=").append(state);
        sb.append(", areaId=").append(areaId);
        sb.append(", createTime=").append(createTime);
        sb.append(", type=").append(type);
        sb.append(", see=").append(see);
        sb.append(", score=").append(score);
        sb.append(", title=").append(title);
        sb.append(", qqGroup=").append(qqGroup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}