package com.jyt.bbs.model.entity;

import java.io.Serializable;
import java.util.Date;

public class PunishmentRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment_record.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment_record.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment_record.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment_record.punishmentcol
     *
     * @mbggenerated
     */
    private String punishmentcol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment_record.punishment_day
     *
     * @mbggenerated
     */
    private Integer punishmentDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punishment_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table punishment_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment_record.id
     *
     * @return the value of punishment_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment_record.id
     *
     * @param id the value for punishment_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment_record.user_id
     *
     * @return the value of punishment_record.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment_record.user_id
     *
     * @param userId the value for punishment_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment_record.reason
     *
     * @return the value of punishment_record.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment_record.reason
     *
     * @param reason the value for punishment_record.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment_record.time
     *
     * @return the value of punishment_record.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment_record.time
     *
     * @param time the value for punishment_record.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment_record.punishmentcol
     *
     * @return the value of punishment_record.punishmentcol
     *
     * @mbggenerated
     */
    public String getPunishmentcol() {
        return punishmentcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment_record.punishmentcol
     *
     * @param punishmentcol the value for punishment_record.punishmentcol
     *
     * @mbggenerated
     */
    public void setPunishmentcol(String punishmentcol) {
        this.punishmentcol = punishmentcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment_record.punishment_day
     *
     * @return the value of punishment_record.punishment_day
     *
     * @mbggenerated
     */
    public Integer getPunishmentDay() {
        return punishmentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment_record.punishment_day
     *
     * @param punishmentDay the value for punishment_record.punishment_day
     *
     * @mbggenerated
     */
    public void setPunishmentDay(Integer punishmentDay) {
        this.punishmentDay = punishmentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punishment_record.create_time
     *
     * @return the value of punishment_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punishment_record.create_time
     *
     * @param createTime the value for punishment_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishment_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", reason=").append(reason);
        sb.append(", time=").append(time);
        sb.append(", punishmentcol=").append(punishmentcol);
        sb.append(", punishmentDay=").append(punishmentDay);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}