package com.jyt.bbs.model.entity;

import java.io.Serializable;
import java.util.Date;

public class Subject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.right_answer
     *
     * @mbggenerated
     */
    private String rightAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.answers_json
     *
     * @mbggenerated
     */
    private String answersJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.kind
     *
     * @mbggenerated
     */
    private Integer kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subject
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.id
     *
     * @return the value of subject.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.id
     *
     * @param id the value for subject.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.type
     *
     * @return the value of subject.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.type
     *
     * @param type the value for subject.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.title
     *
     * @return the value of subject.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.title
     *
     * @param title the value for subject.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.right_answer
     *
     * @return the value of subject.right_answer
     *
     * @mbggenerated
     */
    public String getRightAnswer() {
        return rightAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.right_answer
     *
     * @param rightAnswer the value for subject.right_answer
     *
     * @mbggenerated
     */
    public void setRightAnswer(String rightAnswer) {
        this.rightAnswer = rightAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.answers_json
     *
     * @return the value of subject.answers_json
     *
     * @mbggenerated
     */
    public String getAnswersJson() {
        return answersJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.answers_json
     *
     * @param answersJson the value for subject.answers_json
     *
     * @mbggenerated
     */
    public void setAnswersJson(String answersJson) {
        this.answersJson = answersJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.create_time
     *
     * @return the value of subject.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.create_time
     *
     * @param createTime the value for subject.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.kind
     *
     * @return the value of subject.kind
     *
     * @mbggenerated
     */
    public Integer getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.kind
     *
     * @param kind the value for subject.kind
     *
     * @mbggenerated
     */
    public void setKind(Integer kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", title=").append(title);
        sb.append(", rightAnswer=").append(rightAnswer);
        sb.append(", answersJson=").append(answersJson);
        sb.append(", createTime=").append(createTime);
        sb.append(", kind=").append(kind);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}