package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.AdClick;
import java.util.List;

public interface AdClickMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_click
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_click
     *
     * @mbggenerated
     */
    int insert(AdClick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_click
     *
     * @mbggenerated
     */
    AdClick selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_click
     *
     * @mbggenerated
     */
    List<AdClick> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_click
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdClick record);
}