package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.AdminLog;
import java.util.List;

public interface AdminLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    int insert(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    AdminLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    List<AdminLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminLog record);
}