package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.AuthGroupAccess;
import java.util.List;

public interface AuthGroupAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_access
     *
     * @mbggenerated
     */
    int insert(AuthGroupAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_access
     *
     * @mbggenerated
     */
    List<AuthGroupAccess> selectAll();
}