package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.AuthRule;
import java.util.List;

public interface AuthRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_rule
     *
     * @mbggenerated
     */
    int insert(AuthRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_rule
     *
     * @mbggenerated
     */
    AuthRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_rule
     *
     * @mbggenerated
     */
    List<AuthRule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthRule record);
}