package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.Ems;
import java.util.List;

public interface EmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems
     *
     * @mbggenerated
     */
    int insert(Ems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems
     *
     * @mbggenerated
     */
    Ems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems
     *
     * @mbggenerated
     */
    List<Ems> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ems record);
}