package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.Floor;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FloorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor
     *
     * @mbggenerated
     */
    int insert(Floor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor
     *
     * @mbggenerated
     */
    Floor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor
     *
     * @mbggenerated
     */
    List<Floor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Floor record);

    List<Floor> listFloorByPostIdOrderByDate(@Param("postId") Integer postId);

    int addFloor(Floor floor);

    Floor getFloorByPostIdAndNum(@Param("postId")Integer postId,@Param("num")String num);

    Floor getFloorByUserIdAndPostId(@Param("userId")Integer userId,@Param("postId")Integer postId);
}