package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.FlywaySchemaHistory;
import java.util.List;

public interface FlywaySchemaHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbggenerated
     */
    int insert(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbggenerated
     */
    FlywaySchemaHistory selectByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbggenerated
     */
    List<FlywaySchemaHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FlywaySchemaHistory record);
}