package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.Message;
import io.swagger.models.auth.In;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    List<Message> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Message record);

    List<Message> listUnReadMessage(@Param("fromId")Integer fromId, @Param("toId")Integer toId);

    int getUnReadMessageCount(@Param("userId")Integer userId);

    List<Message> listHistoryMessage(@Param("userId")Integer userId,@Param("friendId")Integer friendId);

    int setMessageStateToRead(@Param("messageIds")List<Integer> messageIds);
}