package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.Post;
import com.jyt.bbs.model.vo.PostDetail;
import com.jyt.bbs.model.vo.PostThumb;
import io.swagger.models.auth.In;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    List<Post> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Post record);

    List<PostThumb> listPostByAreaIdOrderByDate(@Param("areaId") Integer areaId, @Param("date") Date date, @Param("keyword")String keyword);

    PostDetail getPostDetail( @Param("postId")Integer postId);

    List<PostThumb> listPostThumbByUserId(@Param("userId")Integer userId);
}