package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.PunishmentRecord;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PunishmentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishment_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishment_record
     *
     * @mbggenerated
     */
    int insert(PunishmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishment_record
     *
     * @mbggenerated
     */
    PunishmentRecord selectByPrimaryKey(@Param("id") Integer id, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishment_record
     *
     * @mbggenerated
     */
    List<PunishmentRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishment_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PunishmentRecord record);
}