package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.ScoreWater;
import java.util.List;

public interface ScoreWaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_water
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_water
     *
     * @mbggenerated
     */
    int insert(ScoreWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_water
     *
     * @mbggenerated
     */
    ScoreWater selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_water
     *
     * @mbggenerated
     */
    List<ScoreWater> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_water
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScoreWater record);
}