package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.SubjectRecord;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_record
     *
     * @mbggenerated
     */
    int insert(SubjectRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_record
     *
     * @mbggenerated
     */
    SubjectRecord selectByPrimaryKey(@Param("id") Integer id, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_record
     *
     * @mbggenerated
     */
    List<SubjectRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SubjectRecord record);
}