package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.System;
import java.util.List;

public interface SystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbggenerated
     */
    int insert(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbggenerated
     */
    System selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbggenerated
     */
    List<System> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(System record);
}