package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.UserArea;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("areaId") Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_area
     *
     * @mbggenerated
     */
    int insert(UserArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_area
     *
     * @mbggenerated
     */
    List<UserArea> selectAll();
}