package com.jyt.bbs.dao;

import com.jyt.bbs.model.entity.UserShop;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shop
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("shopId") Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shop
     *
     * @mbggenerated
     */
    int insert(UserShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shop
     *
     * @mbggenerated
     */
    List<UserShop> selectAll();
}